# Generated by Django 5.1.7 on 2026-08-17 19:18

import aplicaciones.condominio.models
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='EstadoCondominio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clave', models.CharField(max_length=50)),
                ('descripcion', models.CharField(max_length=100)),
                ('orden', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
            options={
                'verbose_name': 'Estado Condominio',
            },
        ),
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clave', models.CharField(max_length=50)),
                ('descripcion', models.CharField(max_length=100)),
                ('orden', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
            options={
                'verbose_name': 'Rol',
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True, null=True)),
                ('email_whatsapp', models.CharField(help_text='Ingrese su correo electrónico o número de WhatsApp (solo números)', max_length=50, unique=True, verbose_name='correo o whatsapp')),
                ('nombre_completo', models.CharField(max_length=150, verbose_name='nombre completo')),
                ('esta_activo', models.BooleanField(default=True, verbose_name='activo')),
                ('is_staff', models.BooleanField(blank=True, default=False, null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
                ('usuario_creo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_creado', to=settings.AUTH_USER_MODEL)),
                ('usuario_modifico', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_modificado', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'usuario',
                'verbose_name_plural': 'usuarios',
                'ordering': ['nombre_completo'],
            },
        ),
        migrations.CreateModel(
            name='Comite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True, null=True)),
                ('aplica_desde', models.DateField(help_text='Fecha inicial de vigencia de la tabla correspondiente')),
                ('aplica_hasta', models.DateField(blank=True, help_text='Fecha final de vigencia de la tabla correspondiente', null=True)),
                ('nombre', models.CharField(help_text='Nombre que identifica el comite', max_length=50)),
                ('activo', models.BooleanField(default=True, help_text='Indica si el rol está vigente en la sesión actual')),
                ('usuario_creo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_creado', to=settings.AUTH_USER_MODEL)),
                ('usuario_modifico', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_modificado', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Condominio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True, null=True)),
                ('nombre', models.CharField(help_text='Máximo 50 caracteres', max_length=50, unique=True)),
                ('nombre_corto', models.CharField(default='', help_text='Máximo 20 caracteres', max_length=20, unique=True)),
                ('direccion', models.CharField(max_length=100, unique=True)),
                ('inicio_servicio', models.DateField()),
                ('usuario_creo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_creado', to=settings.AUTH_USER_MODEL)),
                ('usuario_modifico', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_modificado', to=settings.AUTH_USER_MODEL)),
                ('estado_condominio', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='condominio.estadocondominio')),
            ],
            options={
                'verbose_name': 'Condominio',
                'verbose_name_plural': 'Condominios',
            },
        ),
        migrations.CreateModel(
            name='ComiteComposicion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True, null=True)),
                ('funcion_integrante', models.CharField(help_text='Indicacion del rol o funcion del miembro del comite', max_length=50)),
                ('activo', models.BooleanField(default=True, help_text='Indica si el ese miembro del comite esta activo o no')),
                ('comite', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='condominio.comite')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('usuario_creo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_creado', to=settings.AUTH_USER_MODEL)),
                ('usuario_modifico', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_modificado', to=settings.AUTH_USER_MODEL)),
                ('condominio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='condominio.condominio')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='comite',
            name='condominio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='condominio.condominio'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='condominio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='condominio.condominio'),
        ),
        migrations.CreateModel(
            name='Propiedad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True, null=True)),
                ('nombre', models.CharField(max_length=50)),
                ('direccion', models.CharField(max_length=100)),
                ('condominio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='condominio.condominio')),
                ('propietario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='propiedades', to=settings.AUTH_USER_MODEL)),
                ('usuario_creo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_creado', to=settings.AUTH_USER_MODEL)),
                ('usuario_modifico', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_modificado', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Propiedad',
                'verbose_name_plural': 'Propiedades',
            },
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True, null=True)),
                ('nombre', models.CharField(max_length=50)),
                ('direccion', models.CharField(max_length=100)),
                ('titular', models.CharField(max_length=50)),
                ('celular', models.CharField(max_length=30, unique=True)),
                ('correo', models.CharField(max_length=30, unique=True)),
                ('comentarios', models.CharField(max_length=500)),
                ('aplica_desde', models.DateField()),
                ('aplica_hasta', models.DateField(blank=True, null=True)),
                ('condominio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='condominio.condominio')),
                ('usuario_creo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_creado', to=settings.AUTH_USER_MODEL)),
                ('usuario_modifico', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_modificado', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Proveedor',
                'verbose_name_plural': 'Proveedores',
            },
        ),
        migrations.CreateModel(
            name='TipoCuota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True, null=True)),
                ('clave', models.CharField(max_length=50)),
                ('descripcion', models.CharField(max_length=100)),
                ('orden', models.DecimalField(decimal_places=2, max_digits=5)),
                ('condominio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='condominio.condominio')),
                ('usuario_creo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_creado', to=settings.AUTH_USER_MODEL)),
                ('usuario_modifico', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_modificado', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Tipo de Cuota',
            },
        ),
        migrations.CreateModel(
            name='TipoFrecuencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True, null=True)),
                ('clave', models.CharField(max_length=50)),
                ('descripcion', models.CharField(max_length=100)),
                ('orden', models.DecimalField(decimal_places=2, max_digits=5)),
                ('condominio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='condominio.condominio')),
                ('usuario_creo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_creado', to=settings.AUTH_USER_MODEL)),
                ('usuario_modifico', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_modificado', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Tipo Frecuencia de Pago',
            },
        ),
        migrations.CreateModel(
            name='Cuota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True, null=True)),
                ('nombre', models.CharField(max_length=30)),
                ('importe', models.DecimalField(decimal_places=2, max_digits=12)),
                ('aplica_desde', models.DateField()),
                ('aplica_hasta', models.DateField(blank=True, null=True)),
                ('condominio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='condominio.condominio')),
                ('usuario_creo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_creado', to=settings.AUTH_USER_MODEL)),
                ('usuario_modifico', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_modificado', to=settings.AUTH_USER_MODEL)),
                ('tipo_cuota', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='condominio.tipocuota')),
                ('frecuencia', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='condominio.tipofrecuencia')),
            ],
            options={
                'verbose_name': 'Cuota',
                'verbose_name_plural': 'Cuotas',
            },
        ),
        migrations.CreateModel(
            name='TipoGasto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True, null=True)),
                ('clave', models.CharField(max_length=50)),
                ('descripcion', models.CharField(max_length=100)),
                ('orden', models.DecimalField(decimal_places=2, max_digits=5)),
                ('quien_autoriza', models.CharField(blank=True, max_length=50, null=True)),
                ('condominio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='condominio.condominio')),
                ('usuario_creo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_creado', to=settings.AUTH_USER_MODEL)),
                ('usuario_modifico', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_modificado', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Tipo Gasto',
                'verbose_name_plural': 'Tipos de Gastos',
            },
        ),
        migrations.CreateModel(
            name='GastoPagado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True, null=True)),
                ('importe_pagado', models.DecimalField(decimal_places=2, max_digits=12)),
                ('fecha', models.DateField()),
                ('comprobante', models.CharField(max_length=100)),
                ('quien_autorizo', models.DateField(blank=True, null=True)),
                ('cuando_autorizo', models.DateField(blank=True, null=True)),
                ('gasto_comprobante', models.ImageField(blank=True, null=True, upload_to=aplicaciones.condominio.models.ruta_comprobante_condominio)),
                ('condominio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='condominio.condominio')),
                ('usuario_creo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_creado', to=settings.AUTH_USER_MODEL)),
                ('usuario_modifico', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_modificado', to=settings.AUTH_USER_MODEL)),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='condominio.proveedor')),
                ('gasto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='condominio.tipogasto')),
            ],
            options={
                'verbose_name': 'Gasto Pagado',
                'verbose_name_plural': 'Gastos Pagados',
            },
        ),
        migrations.CreateModel(
            name='TipoPeriodoCuota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True, null=True)),
                ('clave', models.CharField(max_length=50)),
                ('descripcion', models.CharField(max_length=100)),
                ('orden', models.DecimalField(decimal_places=2, max_digits=5)),
                ('condominio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='condominio.condominio')),
                ('usuario_creo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_creado', to=settings.AUTH_USER_MODEL)),
                ('usuario_modifico', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_modificado', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Tipo Periodo de Cuota',
            },
        ),
        migrations.CreateModel(
            name='CuotaCobrada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True, null=True)),
                ('importe_cobrado', models.DecimalField(decimal_places=2, max_digits=12)),
                ('fecha', models.DateField()),
                ('comprobante', models.CharField(max_length=200)),
                ('cuota_comprobante', models.ImageField(blank=True, null=True, upload_to=aplicaciones.condominio.models.ruta_comprobante_condominio)),
                ('condominio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='condominio.condominio')),
                ('usuario_creo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_creado', to=settings.AUTH_USER_MODEL)),
                ('usuario_modifico', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_modificado', to=settings.AUTH_USER_MODEL)),
                ('propiedad', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='condominio.propiedad')),
                ('tipo_cuota', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='condominio.tipocuota')),
                ('periodo_cuota', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='condominio.tipoperiodocuota')),
            ],
            options={
                'verbose_name': 'Cuota Cobrada',
                'verbose_name_plural': 'Cuotas Cobradas',
            },
        ),
        migrations.CreateModel(
            name='UsuarioRol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True, null=True)),
                ('fecha_fin', models.DateField(blank=True, help_text='Fecha en la que concluye la vigencia del rol (Null indica vigencia actual)', null=True)),
                ('activo', models.BooleanField(default=True, help_text='Indica si el rol está vigente en la sesión actual')),
                ('condominio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usuarios', to='condominio.condominio')),
                ('rol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usuarios', to='condominio.rol')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roles', to=settings.AUTH_USER_MODEL)),
                ('usuario_creo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_creado', to=settings.AUTH_USER_MODEL)),
                ('usuario_modifico', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_modificado', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Usuario Rol',
                'constraints': [models.UniqueConstraint(condition=models.Q(('activo', True)), fields=('usuario', 'condominio', 'rol'), name='uq_usuario_condominio_rol_activo')],
            },
        ),
    ]
