# Generated by Django 5.1.7 on 2025-06-22 18:27

import aplicaciones.condominio.models
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now_add=True, null=True)),
                ('email_whatsapp', models.CharField(help_text='Ingrese su correo electrónico o número de WhatsApp (solo números)', max_length=50, unique=True, verbose_name='correo o whatsapp')),
                ('nombre_completo', models.CharField(max_length=150, verbose_name='nombre completo')),
                ('tipo_usuario', models.CharField(choices=[('ADMIN', 'Administrador'), ('PROPIETARIO', 'Propietario'), ('CONSERJE', 'Conserje')], default='PROPIETARIO', max_length=20, verbose_name='tipo de usuario')),
                ('esta_activo', models.BooleanField(default=True, verbose_name='activo')),
                ('is_staff', models.BooleanField(blank=True, default=False, null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
                ('usuario_creo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_creado', to=settings.AUTH_USER_MODEL)),
                ('usuario_modifico', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_modificado', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'usuario',
                'verbose_name_plural': 'usuarios',
                'ordering': ['nombre_completo'],
            },
        ),
        migrations.CreateModel(
            name='CasaDepartamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now_add=True, null=True)),
                ('nombre', models.CharField(max_length=50)),
                ('direccion', models.CharField(max_length=100)),
                ('titular', models.CharField(max_length=50)),
                ('celular', models.CharField(max_length=30, unique=True)),
                ('correo', models.EmailField(default='', max_length=30, unique=True)),
                ('usuario_creo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_creado', to=settings.AUTH_USER_MODEL)),
                ('usuario_modifico', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_modificado', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Casa Departamento',
                'verbose_name_plural': 'Casas Departamentos',
            },
        ),
        migrations.AddField(
            model_name='usuario',
            name='casa_departamento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='casa_departamento', to='condominio.casadepartamento', verbose_name='casa departamento asignado'),
        ),
        migrations.CreateModel(
            name='Condominio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now_add=True, null=True)),
                ('nombre', models.CharField(help_text='Máximo 50 caracteres', max_length=50, unique=True)),
                ('nombre_corto', models.CharField(default='', help_text='Máximo 20 caracteres', max_length=20, unique=True)),
                ('direccion', models.CharField(max_length=100, unique=True)),
                ('inicio_servicio', models.DateField()),
                ('usuario_creo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_creado', to=settings.AUTH_USER_MODEL)),
                ('usuario_modifico', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_modificado', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Condominio',
                'verbose_name_plural': 'Condominios',
            },
        ),
        migrations.AddField(
            model_name='casadepartamento',
            name='condominio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='condominio.condominio'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='condominio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='usuarios', to='condominio.condominio', verbose_name='condominio al que pertenece'),
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now_add=True, null=True)),
                ('nombre', models.CharField(max_length=50)),
                ('direccion', models.CharField(max_length=100)),
                ('titular', models.CharField(max_length=50)),
                ('celular', models.CharField(max_length=30, unique=True)),
                ('correo', models.CharField(max_length=30, unique=True)),
                ('comentarios', models.CharField(max_length=500)),
                ('aplica_desde', models.DateField()),
                ('aplica_hasta', models.DateField(blank=True, null=True)),
                ('condominio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='condominio.condominio')),
                ('usuario_creo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_creado', to=settings.AUTH_USER_MODEL)),
                ('usuario_modifico', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_modificado', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Proveedor',
                'verbose_name_plural': 'Proveedores',
            },
        ),
        migrations.CreateModel(
            name='TipoCuota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now_add=True, null=True)),
                ('clave', models.CharField(max_length=50)),
                ('descripcion', models.CharField(max_length=100)),
                ('orden', models.DecimalField(decimal_places=2, max_digits=5)),
                ('usuario_creo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_creado', to=settings.AUTH_USER_MODEL)),
                ('usuario_modifico', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_modificado', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Tipo de Cuota',
            },
        ),
        migrations.CreateModel(
            name='TipoEstadoCondominio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now_add=True, null=True)),
                ('clave', models.CharField(max_length=50)),
                ('descripcion', models.CharField(max_length=100)),
                ('orden', models.DecimalField(decimal_places=2, max_digits=5)),
                ('usuario_creo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_creado', to=settings.AUTH_USER_MODEL)),
                ('usuario_modifico', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_modificado', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Tipo Estado Condominio',
            },
        ),
        migrations.AddField(
            model_name='condominio',
            name='estado_condominio',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='condominio.tipoestadocondominio'),
        ),
        migrations.CreateModel(
            name='TipoFrecuencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now_add=True, null=True)),
                ('clave', models.CharField(max_length=50)),
                ('descripcion', models.CharField(max_length=100)),
                ('orden', models.DecimalField(decimal_places=2, max_digits=5)),
                ('usuario_creo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_creado', to=settings.AUTH_USER_MODEL)),
                ('usuario_modifico', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_modificado', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Tipo Frecuencia de Pago',
            },
        ),
        migrations.CreateModel(
            name='Cuota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now_add=True, null=True)),
                ('nombre', models.CharField(max_length=30)),
                ('importe', models.DecimalField(decimal_places=2, max_digits=12)),
                ('aplica_desde', models.DateField()),
                ('aplica_hasta', models.DateField(blank=True, null=True)),
                ('condominio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='condominio.condominio')),
                ('usuario_creo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_creado', to=settings.AUTH_USER_MODEL)),
                ('usuario_modifico', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_modificado', to=settings.AUTH_USER_MODEL)),
                ('tipo_cuota', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='condominio.tipocuota')),
                ('frecuencia', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='condominio.tipofrecuencia')),
            ],
            options={
                'verbose_name': 'Cuota',
                'verbose_name_plural': 'Cuotas',
            },
        ),
        migrations.CreateModel(
            name='TipoGasto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now_add=True, null=True)),
                ('clave', models.CharField(max_length=50)),
                ('descripcion', models.CharField(max_length=100)),
                ('orden', models.DecimalField(decimal_places=2, max_digits=5)),
                ('quien_autoriza', models.CharField(blank=True, max_length=50, null=True)),
                ('condominio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='condominio.condominio')),
                ('usuario_creo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_creado', to=settings.AUTH_USER_MODEL)),
                ('usuario_modifico', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_modificado', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Tipo Gasto',
                'verbose_name_plural': 'Tipos de Gastos',
            },
        ),
        migrations.CreateModel(
            name='GastoPagado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now_add=True, null=True)),
                ('importe_pagado', models.DecimalField(decimal_places=2, max_digits=12)),
                ('fecha', models.DateField()),
                ('comprobante', models.CharField(max_length=100)),
                ('quien_autorizo', models.DateField(blank=True, null=True)),
                ('cuando_autorizo', models.DateField(blank=True, null=True)),
                ('gasto_comprobante', models.ImageField(blank=True, null=True, upload_to=aplicaciones.condominio.models.ruta_comprobante_condominio)),
                ('condominio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='condominio.condominio')),
                ('usuario_creo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_creado', to=settings.AUTH_USER_MODEL)),
                ('usuario_modifico', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_modificado', to=settings.AUTH_USER_MODEL)),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='condominio.proveedor')),
                ('gasto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='condominio.tipogasto')),
            ],
            options={
                'verbose_name': 'Gasto Pagado',
                'verbose_name_plural': 'Gastos Pagados',
            },
        ),
        migrations.CreateModel(
            name='TipoPeriodoCuota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now_add=True, null=True)),
                ('clave', models.CharField(max_length=50)),
                ('descripcion', models.CharField(max_length=100)),
                ('orden', models.DecimalField(decimal_places=2, max_digits=5)),
                ('usuario_creo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_creado', to=settings.AUTH_USER_MODEL)),
                ('usuario_modifico', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_modificado', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Tipo Periodo de Cuota',
            },
        ),
        migrations.CreateModel(
            name='CuotaCobrada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now_add=True, null=True)),
                ('importe_cobrado', models.DecimalField(decimal_places=2, max_digits=12)),
                ('fecha', models.DateField()),
                ('comprobante', models.CharField(max_length=200)),
                ('cuota_comprobante', models.ImageField(blank=True, null=True, upload_to=aplicaciones.condominio.models.ruta_comprobante_condominio)),
                ('casa_departamento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='condominio.casadepartamento')),
                ('condominio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='condominio.condominio')),
                ('usuario_creo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_creado', to=settings.AUTH_USER_MODEL)),
                ('usuario_modifico', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_modificado', to=settings.AUTH_USER_MODEL)),
                ('tipo_cuota', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='condominio.tipocuota')),
                ('periodo_cuota', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='condominio.tipoperiodocuota')),
            ],
            options={
                'verbose_name': 'Cuota Cobrada',
                'verbose_name_plural': 'Cuotas Cobradas',
            },
        ),
        migrations.CreateModel(
            name='TipoRol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now_add=True, null=True)),
                ('clave', models.CharField(max_length=50)),
                ('descripcion', models.CharField(max_length=100)),
                ('orden', models.DecimalField(decimal_places=2, max_digits=5)),
                ('usuario_creo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_creado', to=settings.AUTH_USER_MODEL)),
                ('usuario_modifico', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_modificado', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Tipo Rol',
            },
        ),
        migrations.AddField(
            model_name='casadepartamento',
            name='rol',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='condominio.tiporol'),
        ),
    ]
