# Generated by Django 5.1.7 on 2026-08-31 03:29

import aplicaciones.condominio.models
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='EstadoCondominio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clave', models.CharField(max_length=50)),
                ('descripcion', models.CharField(max_length=100)),
                ('orden', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
            options={
                'verbose_name': 'Estado Condominio',
            },
        ),
        migrations.CreateModel(
            name='FrecuenciaCuota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clave', models.CharField(help_text=' solo pueden ser MENSUAL o UNICA', max_length=50)),
                ('descripcion', models.CharField(help_text=' descripcion para ser MENSUAL o UNICA', max_length=100)),
                ('orden', models.DecimalField(decimal_places=2, help_text=' Para ordenar en listas ', max_digits=5)),
                ('unidad_tiempo', models.CharField(help_text=' Para cobrar cada MES o en un DIA', max_length=20)),
            ],
            options={
                'verbose_name': 'Frecuencia de Cuota',
            },
        ),
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clave', models.CharField(max_length=50, unique=True)),
                ('descripcion', models.CharField(max_length=100)),
                ('orden', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
            options={
                'verbose_name': 'Rol',
            },
        ),
        migrations.CreateModel(
            name='SituacionProveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clave', models.CharField(max_length=50)),
                ('descripcion', models.CharField(max_length=100)),
                ('orden', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
            options={
                'verbose_name': 'Situacion Proveedor',
            },
        ),
        migrations.CreateModel(
            name='TipoGasto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clave', models.CharField(max_length=50)),
                ('descripcion', models.CharField(max_length=100)),
                ('orden', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
            options={
                'verbose_name': 'Tipo Gasto',
                'verbose_name_plural': 'Tipos de Gastos',
            },
        ),
        migrations.CreateModel(
            name='TipoToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clave', models.CharField(max_length=50, unique=True)),
                ('descripcion', models.CharField(max_length=100)),
                ('orden', models.DecimalField(decimal_places=2, max_digits=5)),
                ('duracion_minutos', models.PositiveIntegerField(help_text='Duración del token en minutos')),
            ],
            options={
                'verbose_name': 'Tipo Token',
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True, null=True)),
                ('email_whatsapp', models.CharField(help_text='Ingrese su correo electrónico o número de WhatsApp (solo números)', max_length=50, unique=True, verbose_name='correo o whatsapp')),
                ('nombre_completo', models.CharField(max_length=150, verbose_name='nombre completo')),
                ('esta_activo', models.BooleanField(default=True, verbose_name='activo')),
                ('is_staff', models.BooleanField(blank=True, default=False, null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
                ('usuario_creo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_creado', to=settings.AUTH_USER_MODEL)),
                ('usuario_modifico', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_modificado', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'usuario',
                'verbose_name_plural': 'usuarios',
                'ordering': ['nombre_completo'],
            },
        ),
        migrations.CreateModel(
            name='Condominio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True, null=True)),
                ('nombre', models.CharField(help_text='Máximo 50 caracteres', max_length=50, unique=True)),
                ('nombre_corto', models.CharField(default='', help_text='Máximo 20 caracteres', max_length=20, unique=True)),
                ('direccion', models.CharField(max_length=100, unique=True)),
                ('inicio_servicio', models.DateField()),
                ('usuario_creo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_creado', to=settings.AUTH_USER_MODEL)),
                ('usuario_modifico', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_modificado', to=settings.AUTH_USER_MODEL)),
                ('estado_condominio', models.ForeignKey(default=aplicaciones.condominio.models.Condominio.get_estado_activo, on_delete=django.db.models.deletion.PROTECT, to='condominio.estadocondominio')),
            ],
            options={
                'verbose_name': 'Condominio',
                'verbose_name_plural': 'Condominios',
            },
        ),
        migrations.AddField(
            model_name='usuario',
            name='condominio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='condominio.condominio'),
        ),
        migrations.CreateModel(
            name='Cuota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True, null=True)),
                ('nombre', models.CharField(help_text='En un nombre que se le puede dar a esa cuota', max_length=100)),
                ('importe', models.DecimalField(decimal_places=2, help_text='Se debe indicar un importe para cualquiera de las cuotas ', max_digits=12)),
                ('activo', models.BooleanField(default=True, help_text='Indica la cuota está activo o no')),
                ('aplica_desde', models.DateField(help_text='Fecha inicial de exigibilidad de la cuota puede se menor,  mayor o igual a la fecha del sistema')),
                ('aplica_hasta', models.DateField(help_text='Fecha final de exigibilidad de la cuota, debe ser mayor a la fecha inicial y puede se menor,  mayor o igual a la fecha del sistema')),
                ('condominio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='condominio.condominio')),
                ('usuario_creo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_creado', to=settings.AUTH_USER_MODEL)),
                ('usuario_modifico', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_modificado', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Cuota',
                'verbose_name_plural': 'Cuotas',
            },
        ),
        migrations.CreateModel(
            name='Propiedad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True, null=True)),
                ('nombre', models.CharField(max_length=50)),
                ('direccion', models.CharField(max_length=100)),
                ('condominio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='condominio.condominio')),
                ('propietario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='propiedades', to=settings.AUTH_USER_MODEL)),
                ('usuario_creo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_creado', to=settings.AUTH_USER_MODEL)),
                ('usuario_modifico', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_modificado', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Propiedad',
                'verbose_name_plural': 'Propiedades',
            },
        ),
        migrations.CreateModel(
            name='CuotaExigible',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True, null=True)),
                ('fecha_exigibilidad', models.DateField(help_text='Fecha en la que sera exigible la cuota y se debera de pagar en caso de mensual sera al inicio de mes')),
                ('importe_cuota', models.DecimalField(decimal_places=2, help_text='Importe a pagar de la cuota', max_digits=12)),
                ('estado', models.CharField(choices=[('E', 'Exigible'), ('P', 'Pagada'), ('C', 'Cancelada')], default='E', help_text='Estado de la exigibilidad de la cuota', max_length=1)),
                ('condominio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='condominio.condominio')),
                ('cuota', models.ForeignKey(help_text='El nombre de la cuota que lleva las condiciones de la cuota', on_delete=django.db.models.deletion.PROTECT, to='condominio.cuota')),
                ('usuario_creo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_creado', to=settings.AUTH_USER_MODEL)),
                ('usuario_modifico', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_modificado', to=settings.AUTH_USER_MODEL)),
                ('propiedad', models.ForeignKey(help_text='Propiedad que debe  pagar la cuota', on_delete=django.db.models.deletion.PROTECT, to='condominio.propiedad')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CuotaCobrada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True, null=True)),
                ('importe_exigible', models.DecimalField(decimal_places=2, help_text='Importe exigible de la cuota', max_digits=12)),
                ('importe_cobrado', models.DecimalField(decimal_places=2, help_text='Importe cobrado de esa cuota', max_digits=12)),
                ('fecha_recepcion', models.DateTimeField(auto_now_add=True, help_text='Sera la fecha y hora de cuando se recibe la cuota no se puede cambiar')),
                ('comprobante', models.CharField(help_text='Es una captura libre de como se comprueba el importe', max_length=100)),
                ('cuota_comprobante', models.ImageField(blank=True, help_text='archivo en formato pdf o jpg solamente', null=True, upload_to=aplicaciones.condominio.models.ruta_comprobante_condominio)),
                ('cuando_valido', models.DateTimeField(blank=True, help_text='Sera la fecha y hora cuando el administrador recibe y valida las cuotas', null=True)),
                ('saldo', models.DecimalField(decimal_places=2, default=0, help_text='Diferencia entre el monto de la cuota definido y lo pagado puede ser a favor o en contra se pasa al siguiente pago', max_digits=12)),
                ('esta_validada', models.BooleanField(default=False)),
                ('condominio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='condominio.condominio')),
                ('quien_recibe', models.ForeignKey(help_text='La persona que recibe la cuota', on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_recibio', to=settings.AUTH_USER_MODEL)),
                ('quien_valido', models.ForeignKey(blank=True, help_text='Sera el administrador', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_valido', to=settings.AUTH_USER_MODEL)),
                ('usuario_creo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_creado', to=settings.AUTH_USER_MODEL)),
                ('usuario_modifico', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_modificado', to=settings.AUTH_USER_MODEL)),
                ('cuota_exigible', models.ForeignKey(help_text='Cuota que se paga', on_delete=django.db.models.deletion.PROTECT, to='condominio.cuotaexigible')),
                ('propiedad', models.ForeignKey(help_text='Propiedad que paga la cuota', on_delete=django.db.models.deletion.PROTECT, to='condominio.propiedad')),
            ],
            options={
                'verbose_name': 'Cuota Cobrada',
                'verbose_name_plural': 'Cuotas Cobradas',
            },
        ),
        migrations.CreateModel(
            name='TipoCuota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clave', models.CharField(help_text=' solo pueden ser ORDINARIA o EXTRAORDINARIA', max_length=50)),
                ('descripcion', models.CharField(help_text=' descripcion para ORDINARIA o EXTRAORDINARIA', max_length=100)),
                ('orden', models.DecimalField(decimal_places=2, max_digits=5)),
                ('frecuencia_cuota', models.ForeignKey(help_text='Solo pueden ser mensual o unica y cobrarse cada mes o en un dia', on_delete=django.db.models.deletion.PROTECT, to='condominio.frecuenciacuota')),
            ],
            options={
                'verbose_name': 'Tipo Cuota',
            },
        ),
        migrations.AddField(
            model_name='cuota',
            name='tipo_cuota',
            field=models.ForeignKey(help_text='Solo pueden ser ordinaria o extraordinaria', on_delete=django.db.models.deletion.PROTECT, to='condominio.tipocuota'),
        ),
        migrations.CreateModel(
            name='TokenUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True, null=True)),
                ('token_hash', models.CharField(help_text='Hash SHA-256 del token temporal', max_length=64)),
                ('fecha_generacion', models.DateTimeField(help_text='Fecha en la que se generó el token temporal para el usuario')),
                ('fecha_expiracion', models.DateTimeField(help_text='Fecha en la que expira el token temporal para el usuario')),
                ('fecha_uso', models.DateTimeField(blank=True, help_text='Fecha y hora en la que se usó el token temporal', null=True)),
                ('fecha_cancelacion', models.DateTimeField(blank=True, help_text='Fecha y hora en la que se canceló el token temporal', null=True)),
                ('condominio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='condominio.condominio')),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='condominio.tipotoken')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('usuario_creo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_creado', to=settings.AUTH_USER_MODEL)),
                ('usuario_modifico', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_modificado', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Token Usuario',
            },
        ),
        migrations.CreateModel(
            name='UsuarioRol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True, null=True)),
                ('fecha_fin', models.DateField(blank=True, help_text='Fecha en la que concluye la vigencia del rol (Null indica vigencia actual)', null=True)),
                ('activo', models.BooleanField(default=True, help_text='Indica si el rol está vigente en la sesión actual')),
                ('condominio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usuarios', to='condominio.condominio')),
                ('rol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usuarios', to='condominio.rol')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roles', to=settings.AUTH_USER_MODEL)),
                ('usuario_creo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_creado', to=settings.AUTH_USER_MODEL)),
                ('usuario_modifico', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_modificado', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Usuario Rol',
            },
        ),
        migrations.AddConstraint(
            model_name='cuota',
            constraint=models.UniqueConstraint(condition=models.Q(('activo', True)), fields=('condominio', 'tipo_cuota'), name='unique_cuota_activa_por_condominio_y_tipo'),
        ),
        migrations.AddConstraint(
            model_name='usuariorol',
            constraint=models.UniqueConstraint(condition=models.Q(('activo', True)), fields=('usuario', 'condominio', 'rol'), name='uq_usuario_condominio_rol_activo'),
        ),
    ]
