# Generated by Django 5.1.7 on 2026-08-19 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('condominio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tokenusuario',
            name='fecha_cancelacion',
            field=models.DateTimeField(blank=True, help_text='Fecha y hora en la que se canceló el token temporal', null=True),
        ),
    ]
