# Generated by Django 5.1.7 on 2026-09-01 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('condominio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cuota',
            name='comentario_cancelacion',
            field=models.CharField(blank=True, help_text='Comentario con el motivo de la cancelacion', max_length=100, null=True),
        ),
    ]
