# Generated by Django 5.1.7 on 2026-09-06 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('condominio', '0002_cuota_comentario_cancelacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='cuotacobrada',
            name='comentario_validacion',
            field=models.CharField(blank=True, help_text='Comentario del administrador al validar el cobro', max_length=100, null=True),
        ),
    ]
